/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/core/AppBar.vue')['default']
    ArticleCard: typeof import('./components/home/ArticleCard.vue')['default']
    Auth: typeof import('./components/friends/Auth.vue')['default']
    Downloads: typeof import('./components/core/Downloads.vue')['default']
    Drawer: typeof import('./components/core/Drawer.vue')['default']
    Fab: typeof import('./components/core/Fab.vue')['default']
    Featured: typeof import('./components/store/Featured.vue')['default']
    Friends: typeof import('./components/core/Friends.vue')['default']
    Game: typeof import('./components/Game.vue')['default']
    GameGroup: typeof import('./components/store/GameGroup.vue')['default']
    Games: typeof import('./components/library/Games.vue')['default']
    GameStore: typeof import('./components/store/GameStore.vue')['default']
    InstallAction: typeof import('./components/library/InstallAction.vue')['default']
    LaunchAction: typeof import('./components/library/LaunchAction.vue')['default']
    LoggedIn: typeof import('./components/friends/LoggedIn.vue')['default']
    LoggedOut: typeof import('./components/friends/LoggedOut.vue')['default']
    News: typeof import('./components/home/News.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row1: typeof import('./components/store/Row1.vue')['default']
    Row2: typeof import('./components/store/Row2.vue')['default']
    Row3: typeof import('./components/store/Row3.vue')['default']
    Row4: typeof import('./components/store/Row4.vue')['default']
    Snackbar: typeof import('./components/core/Snackbar.vue')['default']
    VerifyAction: typeof import('./components/library/VerifyAction.vue')['default']
    View: typeof import('./components/core/View.vue')['default']
  }
}
